### ISSUE TITLE
Regarding document (Not urgent, but might help)

### ISSUE THREAD

**Issue by kevinirlen** [erkens/2fa-text#8]
It might be worth noting inside the documentation, that the User entity has to implement the `Erkens\Security\TwoFactorTextBundle\Model\TwoFactorTextInterface` interface maybe?

Without this, things doesn't work as expected.

Any thoughts @erkens ?

**Comment by kevinirlen** [comment]
I created a pull request for this. If you can review :)

**Comment by erkens** [comment]
Thanks!
